zh:
  languageCode: "zh"
  languageName: "中文"
  weight: 1
  menu:
    main:
      - identifier: "posts"
        name: "文章"
        pageRef: "/posts"
        weight: 1
      - identifier: "about"
        name: "关于"
        pageRef: "/about"
        weight: 2

en:
  languageCode: "en-us"
  languageName: "English"
  weight: 2
  menu:
    main:
      - identifier: "posts"
        name: "Posts"
        pageRef: "/posts"
        weight: 1
      - identifier: "about"
        name: "About"
        pageRef: "/about"
        weight: 2
