keywords = "it, blog"

[header]
logo = "images/logo.png"

[footer]
since = 2024
poweredby = false

[social_media]
[[social_media.items]]
enabled = true
title = 'Github'
icon = 'brand-github'
link = 'https://github.com/ewigl'
